In [3]:
import numpy as np
import pandas as pd
from numpy import loadtxt
#%matplotlib inline
import matplotlib.pyplot as plt
import skfuzzy as fuzz

In [4]:
hcntr = np.array(loadtxt("humidity_cntr.txt", comments="#", delimiter=",", unpack=False))
pcntr = np.array(loadtxt("peekhour_cntr.txt", comments="#", delimiter=",", unpack=False))
rcntr = np.array(loadtxt("rainfall_cntr.txt", comments="#", delimiter=",", unpack=False))
tcntr = np.array(loadtxt("temp_cntr.txt", comments="#", delimiter=",", unpack=False))
wcntr = np.array(loadtxt("wind_cntr.txt", comments="#", delimiter=",", unpack=False))
print (wcntr)

[[ 9.95572003  0.        ]
 [ 2.95720969  0.        ]
 [ 0.61123088  0.        ]
 [ 5.80343385  0.        ]]


In [14]:
def predict_humidity(values):
    # value -numpy array
    xpts = np.zeros(len(values))
    data = np.vstack((values, xpts))
    u, u0, d, jm, p, fpc = fuzz.cluster.cmeans_predict(
        data, hcntr, 1.5, error=0.0005, maxiter=1000)
    cluster_membership = np.argmax(u, axis=0)
    
    return cluster_membership

predict_humidity([70, 120])

array([0, 3])

In [15]:
def predict_peekhour(values):
    xpts = np.zeros(len(values))
    data = np.vstack((values, xpts))
    u, u0, d, jm, p, fpc = fuzz.cluster.cmeans_predict(
        data, pcntr, 1.5, error=0.0005, maxiter=1000)
    cluster_membership = np.argmax(u, axis=0)
    
    return cluster_membership

predict_peekhour([40, 89])


array([2, 0])

In [16]:
def predict_rainfall(values):
    xpts = np.zeros(len(values))
    data = np.vstack((values, xpts))
    u, u0, d, jm, p, fpc = fuzz.cluster.cmeans_predict(
        data, rcntr, 1.5, error=0.0005, maxiter=1000)
    cluster_membership = np.argmax(u, axis=0)
    
    return cluster_membership

predict_rainfall([0, 40])

array([0, 2])

In [17]:
def predict_temp(values):
    xpts = np.zeros(len(values))
    data = np.vstack((values, xpts))
    u, u0, d, jm, p, fpc = fuzz.cluster.cmeans_predict(
        data, tcntr, 1.5, error=0.0005, maxiter=1000)
    cluster_membership = np.argmax(u, axis=0)
    
    return cluster_membership

predict_temp([20, 40])

array([2, 1])

In [19]:
def predict_wind(values):
    xpts = np.zeros(len(values))
    data = np.vstack((values, xpts))
    u, u0, d, jm, p, fpc = fuzz.cluster.cmeans_predict(
        data, wcntr, 1.5, error=0.0005, maxiter=1000)
    cluster_membership = np.argmax(u, axis=0)
    
    return cluster_membership

In [20]:
predict_wind([9, 70])

array([0, 0])